In [1]:
import os
import pandas as pd

df_sample = pd.read_table("Z:/Documents/GitHub/toy/data/distance-data.tsv")
class_pair = list()
i = 0
for class1 in range(104):
  for class2 in range(class1):
    class_pair.append([class1, class2, df_sample.scaledPatristicDistance[i]])
    i=i+1
import pandas as pd

In [2]:
import tensorflow as tf

In [6]:
df_test = pd.read_table("ptm_distance_sample.tsv")
df_test

class1  class2  scaledPatristicDistance
0          1       0                 0.032521
1          2       0                 0.032521
2          2       1                 0.032521
3          3       0                 0.032521
4          3       1                 0.032521
...      ...     ...                      ...
5351     103      98                 0.281768
5352     103      99                 0.279972
5353     103     100                 0.263509
5354     103     101                 0.263509
5355     103     102                 0.284234

[5356 rows x 3 columns]

In [18]:
import tensorflow as tf

lookup = tf.lookup.StaticHashTable(
    tf.lookup.KeyValueTensorInitializer(
    toy.get_key_for_class2distance(df_test.class1, df_test.class2),
    tf.constant(df_test.scaledPatristicDistance)
    ),
    default_value = -1
)


batch_size = 64
import random
pred = random.sample(range(104), k = batch_size)
real = random.sample(range(104), k = batch_size)
pred_onehot = tf.one_hot(pred, 104)
real_onehot = tf.one_hot(real, 104)
distance = toy.get_distance_from_two_classes(real, pred , LOOKUPTB=lookup)

ce_loss = tf.keras.losses.CategoricalCrossentropy()

ce_loss(real_onehot, pred_onehot), ce_loss(real_onehot, pred_onehot, sample_weight = distance)


(<tf.Tensor: shape=(), dtype=float32, numpy=15.614405>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.789507>)

In [19]:
import toy

pdce =toy.PatristicDistanceCrossentropy(map_label_to_distance=lookup,
                                    weight_range = [0, 1])


pdce(real_onehot, pred_onehot)
                            

<tf.Tensor: shape=(), dtype=float32, numpy=5.789507>

In [9]:
lookup[get_key_for_class2distance(real, pred)], get_distance_from_two_classes(real, pred, lookup)

<tf.Tensor: shape=(64,), dtype=float64, numpy=
array([0.2842338, 0.130866 , 0.810142 , 0.1739577, 0.1759178, 0.9805867,
       0.8694284, 0.2799724, 0.799462 , 0.461171 , 0.311403 , 0.0269722,
       0.136282 , 0.4937042, 0.4674582, 0.1490548, 0.5039794, 0.1317477,
       0.0737781, 0.1490706, 0.4790379, 0.0248346, 0.0260794, 0.5251092,
       0.1761407, 0.7768027, 0.2033869, 0.1375207, 0.5112497, 0.029227 ,
       0.4973922, 0.0251069, 0.7839843, 0.5270776, 0.0259562, 0.0276316,
       0.8270118, 0.1507162, 0.5438698, 0.0325205, 0.0277506, 0.4673536,
       0.1337919, 0.8289436, 0.5260387, 0.8694284, 0.1461628, 0.0533559,
       0.2302155, 0.1491927, 0.4904639, 0.1287736, 0.4191143, 0.4373319,
       0.0767066, 0.1526273, 0.0294752, 0.9636292, 0.1531794, 0.4326483,
       0.1526273, 0.1827623, 0.024873 , 0.7837502])>